package com.imooc.jxc.dao;

import com.imooc.jxc.entity.HmMemberScoreLog;
import com.imooc.jxc.entity.HmMemberScoreLogExample;
import java.util.List;
import java.util.Map;

import org.apache.ibatis.annotations.Param;

public interface HmMemberScoreLogMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    long countByExample(HmMemberScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int deleteByExample(HmMemberScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer objid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int insert(HmMemberScoreLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int insertSelective(HmMemberScoreLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    List<HmMemberScoreLog> selectByExample(HmMemberScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    HmMemberScoreLog selectByPrimaryKey(Integer objid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HmMemberScoreLog record, @Param("example") HmMemberScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HmMemberScoreLog record, @Param("example") HmMemberScoreLogExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HmMemberScoreLog record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HmMemberScoreLog record);

    List<Map> queryHmMemberScoreLog(@Param("map") Map map);
}