package com.imooc.jxc.dao;

import com.imooc.jxc.entity.HmMember;
import com.imooc.jxc.entity.HmMemberExample;
import java.util.List;
import org.apache.ibatis.annotations.Param;

public interface HmMemberMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    long countByExample(HmMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int deleteByExample(HmMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int deleteByPrimaryKey(Integer objid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int insert(HmMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int insertSelective(HmMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    List<HmMember> selectByExample(HmMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    HmMember selectByPrimaryKey(Integer objid);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int updateByExampleSelective(@Param("record") HmMember record, @Param("example") HmMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int updateByExample(@Param("record") HmMember record, @Param("example") HmMemberExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKeySelective(HmMember record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    int updateByPrimaryKey(HmMember record);
}