package com.imooc.jxc.entity;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class HmMemberExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public HmMemberExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andObjidIsNull() {
            addCriterion("objid is null");
            return (Criteria) this;
        }

        public Criteria andObjidIsNotNull() {
            addCriterion("objid is not null");
            return (Criteria) this;
        }

        public Criteria andObjidEqualTo(Integer value) {
            addCriterion("objid =", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotEqualTo(Integer value) {
            addCriterion("objid <>", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidGreaterThan(Integer value) {
            addCriterion("objid >", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidGreaterThanOrEqualTo(Integer value) {
            addCriterion("objid >=", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidLessThan(Integer value) {
            addCriterion("objid <", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidLessThanOrEqualTo(Integer value) {
            addCriterion("objid <=", value, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidIn(List<Integer> values) {
            addCriterion("objid in", values, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotIn(List<Integer> values) {
            addCriterion("objid not in", values, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidBetween(Integer value1, Integer value2) {
            addCriterion("objid between", value1, value2, "objid");
            return (Criteria) this;
        }

        public Criteria andObjidNotBetween(Integer value1, Integer value2) {
            addCriterion("objid not between", value1, value2, "objid");
            return (Criteria) this;
        }

        public Criteria andMembernameIsNull() {
            addCriterion("memberName is null");
            return (Criteria) this;
        }

        public Criteria andMembernameIsNotNull() {
            addCriterion("memberName is not null");
            return (Criteria) this;
        }

        public Criteria andMembernameEqualTo(String value) {
            addCriterion("memberName =", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameNotEqualTo(String value) {
            addCriterion("memberName <>", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameGreaterThan(String value) {
            addCriterion("memberName >", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameGreaterThanOrEqualTo(String value) {
            addCriterion("memberName >=", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameLessThan(String value) {
            addCriterion("memberName <", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameLessThanOrEqualTo(String value) {
            addCriterion("memberName <=", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameLike(String value) {
            addCriterion("memberName like", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameNotLike(String value) {
            addCriterion("memberName not like", value, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameIn(List<String> values) {
            addCriterion("memberName in", values, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameNotIn(List<String> values) {
            addCriterion("memberName not in", values, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameBetween(String value1, String value2) {
            addCriterion("memberName between", value1, value2, "membername");
            return (Criteria) this;
        }

        public Criteria andMembernameNotBetween(String value1, String value2) {
            addCriterion("memberName not between", value1, value2, "membername");
            return (Criteria) this;
        }

        public Criteria andMemberphoneIsNull() {
            addCriterion("memberPhone is null");
            return (Criteria) this;
        }

        public Criteria andMemberphoneIsNotNull() {
            addCriterion("memberPhone is not null");
            return (Criteria) this;
        }

        public Criteria andMemberphoneEqualTo(String value) {
            addCriterion("memberPhone =", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneNotEqualTo(String value) {
            addCriterion("memberPhone <>", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneGreaterThan(String value) {
            addCriterion("memberPhone >", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneGreaterThanOrEqualTo(String value) {
            addCriterion("memberPhone >=", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneLessThan(String value) {
            addCriterion("memberPhone <", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneLessThanOrEqualTo(String value) {
            addCriterion("memberPhone <=", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneLike(String value) {
            addCriterion("memberPhone like", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneNotLike(String value) {
            addCriterion("memberPhone not like", value, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneIn(List<String> values) {
            addCriterion("memberPhone in", values, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneNotIn(List<String> values) {
            addCriterion("memberPhone not in", values, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneBetween(String value1, String value2) {
            addCriterion("memberPhone between", value1, value2, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberphoneNotBetween(String value1, String value2) {
            addCriterion("memberPhone not between", value1, value2, "memberphone");
            return (Criteria) this;
        }

        public Criteria andMemberscoreIsNull() {
            addCriterion("memberScore is null");
            return (Criteria) this;
        }

        public Criteria andMemberscoreIsNotNull() {
            addCriterion("memberScore is not null");
            return (Criteria) this;
        }

        public Criteria andMemberscoreEqualTo(Double value) {
            addCriterion("memberScore =", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreNotEqualTo(Double value) {
            addCriterion("memberScore <>", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreGreaterThan(Double value) {
            addCriterion("memberScore >", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreGreaterThanOrEqualTo(Double value) {
            addCriterion("memberScore >=", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreLessThan(Double value) {
            addCriterion("memberScore <", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreLessThanOrEqualTo(Double value) {
            addCriterion("memberScore <=", value, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreIn(List<Double> values) {
            addCriterion("memberScore in", values, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreNotIn(List<Double> values) {
            addCriterion("memberScore not in", values, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreBetween(Double value1, Double value2) {
            addCriterion("memberScore between", value1, value2, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberscoreNotBetween(Double value1, Double value2) {
            addCriterion("memberScore not between", value1, value2, "memberscore");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayIsNull() {
            addCriterion("memberBirthday is null");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayIsNotNull() {
            addCriterion("memberBirthday is not null");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayEqualTo(String value) {
            addCriterion("memberBirthday =", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayNotEqualTo(String value) {
            addCriterion("memberBirthday <>", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayGreaterThan(String value) {
            addCriterion("memberBirthday >", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayGreaterThanOrEqualTo(String value) {
            addCriterion("memberBirthday >=", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayLessThan(String value) {
            addCriterion("memberBirthday <", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayLessThanOrEqualTo(String value) {
            addCriterion("memberBirthday <=", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayLike(String value) {
            addCriterion("memberBirthday like", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayNotLike(String value) {
            addCriterion("memberBirthday not like", value, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayIn(List<String> values) {
            addCriterion("memberBirthday in", values, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayNotIn(List<String> values) {
            addCriterion("memberBirthday not in", values, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayBetween(String value1, String value2) {
            addCriterion("memberBirthday between", value1, value2, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andMemberbirthdayNotBetween(String value1, String value2) {
            addCriterion("memberBirthday not between", value1, value2, "memberbirthday");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNull() {
            addCriterion("createtime is null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIsNotNull() {
            addCriterion("createtime is not null");
            return (Criteria) this;
        }

        public Criteria andCreatetimeEqualTo(Date value) {
            addCriterion("createtime =", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotEqualTo(Date value) {
            addCriterion("createtime <>", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThan(Date value) {
            addCriterion("createtime >", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("createtime >=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThan(Date value) {
            addCriterion("createtime <", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeLessThanOrEqualTo(Date value) {
            addCriterion("createtime <=", value, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeIn(List<Date> values) {
            addCriterion("createtime in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotIn(List<Date> values) {
            addCriterion("createtime not in", values, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeBetween(Date value1, Date value2) {
            addCriterion("createtime between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andCreatetimeNotBetween(Date value1, Date value2) {
            addCriterion("createtime not between", value1, value2, "createtime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNull() {
            addCriterion("updatetime is null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIsNotNull() {
            addCriterion("updatetime is not null");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeEqualTo(Date value) {
            addCriterion("updatetime =", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotEqualTo(Date value) {
            addCriterion("updatetime <>", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThan(Date value) {
            addCriterion("updatetime >", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeGreaterThanOrEqualTo(Date value) {
            addCriterion("updatetime >=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThan(Date value) {
            addCriterion("updatetime <", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeLessThanOrEqualTo(Date value) {
            addCriterion("updatetime <=", value, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeIn(List<Date> values) {
            addCriterion("updatetime in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotIn(List<Date> values) {
            addCriterion("updatetime not in", values, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeBetween(Date value1, Date value2) {
            addCriterion("updatetime between", value1, value2, "updatetime");
            return (Criteria) this;
        }

        public Criteria andUpdatetimeNotBetween(Date value1, Date value2) {
            addCriterion("updatetime not between", value1, value2, "updatetime");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hm_member
     *
     * @mbg.generated do_not_delete_during_merge
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}