package com.imooc.jxc.entity;

import java.util.Date;

public class HmMember {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.objid
     *
     * @mbg.generated
     */
    private Integer objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.memberName
     *
     * @mbg.generated
     */
    private String membername;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.memberPhone
     *
     * @mbg.generated
     */
    private String memberphone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.memberScore
     *
     * @mbg.generated
     */
    private Double memberscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.memberBirthday
     *
     * @mbg.generated
     */
    private String memberbirthday;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member.updatetime
     *
     * @mbg.generated
     */
    private Date updatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public HmMember(Integer objid, String membername, String memberphone, Double memberscore, String memberbirthday, Date createtime, Date updatetime) {
        this.objid = objid;
        this.membername = membername;
        this.memberphone = memberphone;
        this.memberscore = memberscore;
        this.memberbirthday = memberbirthday;
        this.createtime = createtime;
        this.updatetime = updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member
     *
     * @mbg.generated
     */
    public HmMember() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.objid
     *
     * @return the value of hm_member.objid
     *
     * @mbg.generated
     */
    public Integer getObjid() {
        return objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.objid
     *
     * @param objid the value for hm_member.objid
     *
     * @mbg.generated
     */
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.memberName
     *
     * @return the value of hm_member.memberName
     *
     * @mbg.generated
     */
    public String getMembername() {
        return membername;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.memberName
     *
     * @param membername the value for hm_member.memberName
     *
     * @mbg.generated
     */
    public void setMembername(String membername) {
        this.membername = membername == null ? null : membername.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.memberPhone
     *
     * @return the value of hm_member.memberPhone
     *
     * @mbg.generated
     */
    public String getMemberphone() {
        return memberphone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.memberPhone
     *
     * @param memberphone the value for hm_member.memberPhone
     *
     * @mbg.generated
     */
    public void setMemberphone(String memberphone) {
        this.memberphone = memberphone == null ? null : memberphone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.memberScore
     *
     * @return the value of hm_member.memberScore
     *
     * @mbg.generated
     */
    public Double getMemberscore() {
        return memberscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.memberScore
     *
     * @param memberscore the value for hm_member.memberScore
     *
     * @mbg.generated
     */
    public void setMemberscore(Double memberscore) {
        this.memberscore = memberscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.memberBirthday
     *
     * @return the value of hm_member.memberBirthday
     *
     * @mbg.generated
     */
    public String getMemberbirthday() {
        return memberbirthday;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.memberBirthday
     *
     * @param memberbirthday the value for hm_member.memberBirthday
     *
     * @mbg.generated
     */
    public void setMemberbirthday(String memberbirthday) {
        this.memberbirthday = memberbirthday == null ? null : memberbirthday.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.createtime
     *
     * @return the value of hm_member.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.createtime
     *
     * @param createtime the value for hm_member.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member.updatetime
     *
     * @return the value of hm_member.updatetime
     *
     * @mbg.generated
     */
    public Date getUpdatetime() {
        return updatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member.updatetime
     *
     * @param updatetime the value for hm_member.updatetime
     *
     * @mbg.generated
     */
    public void setUpdatetime(Date updatetime) {
        this.updatetime = updatetime;
    }
}