package com.imooc.jxc.entity;

import java.util.Date;

public class HmMemberScoreLog {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.objid
     *
     * @mbg.generated
     */
    private Integer objid;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.phone
     *
     * @mbg.generated
     */
    private String phone;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.memberscore
     *
     * @mbg.generated
     */
    private Double memberscore;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.status
     *
     * @mbg.generated
     */
    private Integer status;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.createtime
     *
     * @mbg.generated
     */
    private Date createtime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column hm_member_score_log.upaatetime
     *
     * @mbg.generated
     */
    private Date upaatetime;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    public HmMemberScoreLog(Integer objid, String phone, Double memberscore, Integer status, Date createtime, Date upaatetime) {
        this.objid = objid;
        this.phone = phone;
        this.memberscore = memberscore;
        this.status = status;
        this.createtime = createtime;
        this.upaatetime = upaatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table hm_member_score_log
     *
     * @mbg.generated
     */
    public HmMemberScoreLog() {
        super();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.objid
     *
     * @return the value of hm_member_score_log.objid
     *
     * @mbg.generated
     */
    public Integer getObjid() {
        return objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.objid
     *
     * @param objid the value for hm_member_score_log.objid
     *
     * @mbg.generated
     */
    public void setObjid(Integer objid) {
        this.objid = objid;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.phone
     *
     * @return the value of hm_member_score_log.phone
     *
     * @mbg.generated
     */
    public String getPhone() {
        return phone;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.phone
     *
     * @param phone the value for hm_member_score_log.phone
     *
     * @mbg.generated
     */
    public void setPhone(String phone) {
        this.phone = phone == null ? null : phone.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.memberscore
     *
     * @return the value of hm_member_score_log.memberscore
     *
     * @mbg.generated
     */
    public Double getMemberscore() {
        return memberscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.memberscore
     *
     * @param memberscore the value for hm_member_score_log.memberscore
     *
     * @mbg.generated
     */
    public void setMemberscore(Double memberscore) {
        this.memberscore = memberscore;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.status
     *
     * @return the value of hm_member_score_log.status
     *
     * @mbg.generated
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.status
     *
     * @param status the value for hm_member_score_log.status
     *
     * @mbg.generated
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.createtime
     *
     * @return the value of hm_member_score_log.createtime
     *
     * @mbg.generated
     */
    public Date getCreatetime() {
        return createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.createtime
     *
     * @param createtime the value for hm_member_score_log.createtime
     *
     * @mbg.generated
     */
    public void setCreatetime(Date createtime) {
        this.createtime = createtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column hm_member_score_log.upaatetime
     *
     * @return the value of hm_member_score_log.upaatetime
     *
     * @mbg.generated
     */
    public Date getUpaatetime() {
        return upaatetime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column hm_member_score_log.upaatetime
     *
     * @param upaatetime the value for hm_member_score_log.upaatetime
     *
     * @mbg.generated
     */
    public void setUpaatetime(Date upaatetime) {
        this.upaatetime = upaatetime;
    }
}